### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Zetazzz** [cansijyun/code-challenge-shawn-tsan#1]
Hi, nice work!

But when it's running on my computer, there's a runtime error popped up when it started:

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading '0')

Call Stack
U1.
chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js (28930:39845)
Generator.next

ce
chrome-extension://egjidjbpglichdcondbcbdnbeeppgdph/inpage.js (28930:37705)

Hope that can be fixed

**Comment by Zetazzz** [comment]
Ah, never mind, I found it's because of one of my chrome plugins. it's not a error from the challenge. 

Thank you!

**Comment by cansijyun** [comment]
> Ah, never mind, I found it's because of one of my chrome plugins. it's not a error from the challenge.
> 
> Thank you!

Thx, I like your company's culture and I added some optimization suggestions to README.md.
